### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by bdochen** [Noxturnix/Signpeaker#3]
I am studying your code ,[https://github.com/bdochen/pydeobfuscate/blob/master/pydeobfuscate.py],and it can not run ,please help me ,thank you

**Comment by Noxturnix** [comment]
Pydeobfuscate only works with codes that being obfuscated from http://pyobfuscate.tk.

The script was my old small project that has been removed from my profile due to the web has shut down since 2018.

**Comment by bdochen** [comment]
Will you share the script again? I think this is better than any other tool ，thank you
